// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constant.proto
package kr.ac.ajou.protocol;

public final class ConstantsProto {
  private ConstantsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConstantProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConstantProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ConstantProtocol.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.ConstantProtocol.Type type = 1;</code>
     * @return The type.
     */
    ConstantsProto.ConstantProtocol.Type getType();
  }
  /**
   * Protobuf type {@code ConstantProtocol}
   */
  public static final class ConstantProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConstantProtocol)
      ConstantProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConstantProtocol.newBuilder() to construct.
    private ConstantProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConstantProtocol() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConstantProtocol();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConstantProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConstantsProto.internal_static_ConstantProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConstantsProto.internal_static_ConstantProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ConstantsProto.ConstantProtocol.class, ConstantsProto.ConstantProtocol.Builder.class);
    }

    /**
     * Protobuf enum {@code ConstantProtocol.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READY = 0;</code>
       */
      READY(0),
      /**
       * <code>NOT_READY = 1;</code>
       */
      NOT_READY(1),
      /**
       * <code>STONE_LOCATION = 2;</code>
       */
      STONE_LOCATION(2),
      /**
       * <code>INIT_STONE = 3;</code>
       */
      INIT_STONE(3),
      /**
       * <code>GAME_STATE = 4;</code>
       */
      GAME_STATE(4),
      /**
       * <code>CLIENT_NUM_MINE = 5;</code>
       */
      CLIENT_NUM_MINE(5),
      /**
       * <code>CLIENT_NUM_OTHER = 6;</code>
       */
      CLIENT_NUM_OTHER(6),
      /**
       * <code>COUNT_DOWN_NUM = 7;</code>
       */
      COUNT_DOWN_NUM(7),
      /**
       * <code>DICE = 8;</code>
       */
      DICE(8),
      /**
       * <code>EXIT = 9;</code>
       */
      EXIT(9),
      /**
       * <code>WIN = 10;</code>
       */
      WIN(10),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>READY = 0;</code>
       */
      public static final int READY_VALUE = 0;
      /**
       * <code>NOT_READY = 1;</code>
       */
      public static final int NOT_READY_VALUE = 1;
      /**
       * <code>STONE_LOCATION = 2;</code>
       */
      public static final int STONE_LOCATION_VALUE = 2;
      /**
       * <code>INIT_STONE = 3;</code>
       */
      public static final int INIT_STONE_VALUE = 3;
      /**
       * <code>GAME_STATE = 4;</code>
       */
      public static final int GAME_STATE_VALUE = 4;
      /**
       * <code>CLIENT_NUM_MINE = 5;</code>
       */
      public static final int CLIENT_NUM_MINE_VALUE = 5;
      /**
       * <code>CLIENT_NUM_OTHER = 6;</code>
       */
      public static final int CLIENT_NUM_OTHER_VALUE = 6;
      /**
       * <code>COUNT_DOWN_NUM = 7;</code>
       */
      public static final int COUNT_DOWN_NUM_VALUE = 7;
      /**
       * <code>DICE = 8;</code>
       */
      public static final int DICE_VALUE = 8;
      /**
       * <code>EXIT = 9;</code>
       */
      public static final int EXIT_VALUE = 9;
      /**
       * <code>WIN = 10;</code>
       */
      public static final int WIN_VALUE = 10;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return READY;
          case 1: return NOT_READY;
          case 2: return STONE_LOCATION;
          case 3: return INIT_STONE;
          case 4: return GAME_STATE;
          case 5: return CLIENT_NUM_MINE;
          case 6: return CLIENT_NUM_OTHER;
          case 7: return COUNT_DOWN_NUM;
          case 8: return DICE;
          case 9: return EXIT;
          case 10: return WIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ConstantsProto.ConstantProtocol.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ConstantProtocol.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.ConstantProtocol.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.ConstantProtocol.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public ConstantsProto.ConstantProtocol.Type getType() {
      @SuppressWarnings("deprecation")
      ConstantsProto.ConstantProtocol.Type result = ConstantsProto.ConstantProtocol.Type.valueOf(type_);
      return result == null ? ConstantsProto.ConstantProtocol.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != ConstantsProto.ConstantProtocol.Type.READY.getNumber()) {
        output.writeEnum(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != ConstantsProto.ConstantProtocol.Type.READY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ConstantsProto.ConstantProtocol)) {
        return super.equals(obj);
      }
      ConstantsProto.ConstantProtocol other = (ConstantsProto.ConstantProtocol) obj;

      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ConstantsProto.ConstantProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ConstantsProto.ConstantProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ConstantsProto.ConstantProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ConstantsProto.ConstantProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ConstantsProto.ConstantProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConstantProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConstantProtocol)
        ConstantsProto.ConstantProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConstantsProto.internal_static_ConstantProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConstantsProto.internal_static_ConstantProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ConstantsProto.ConstantProtocol.class, ConstantsProto.ConstantProtocol.Builder.class);
      }

      // Construct using ConstantsProto.ConstantProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConstantsProto.internal_static_ConstantProtocol_descriptor;
      }

      @java.lang.Override
      public ConstantsProto.ConstantProtocol getDefaultInstanceForType() {
        return ConstantsProto.ConstantProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public ConstantsProto.ConstantProtocol build() {
        ConstantsProto.ConstantProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ConstantsProto.ConstantProtocol buildPartial() {
        ConstantsProto.ConstantProtocol result = new ConstantsProto.ConstantProtocol(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConstantsProto.ConstantProtocol) {
          return mergeFrom((ConstantsProto.ConstantProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConstantsProto.ConstantProtocol other) {
        if (other == ConstantsProto.ConstantProtocol.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ConstantsProto.ConstantProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConstantsProto.ConstantProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.ConstantProtocol.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.ConstantProtocol.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ConstantProtocol.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public ConstantsProto.ConstantProtocol.Type getType() {
        @SuppressWarnings("deprecation")
        ConstantsProto.ConstantProtocol.Type result = ConstantsProto.ConstantProtocol.Type.valueOf(type_);
        return result == null ? ConstantsProto.ConstantProtocol.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.ConstantProtocol.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ConstantsProto.ConstantProtocol.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }

        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ConstantProtocol.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConstantProtocol)
    }

    // @@protoc_insertion_point(class_scope:ConstantProtocol)
    private static final ConstantsProto.ConstantProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ConstantsProto.ConstantProtocol();
    }

    public static ConstantsProto.ConstantProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConstantProtocol>
        PARSER = new com.google.protobuf.AbstractParser<ConstantProtocol>() {
      @java.lang.Override
      public ConstantProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConstantProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConstantProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConstantProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ConstantsProto.ConstantProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConstantProtocol_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConstantProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016constant.proto\"\353\001\n\020ConstantProtocol\022$\n" +
      "\004type\030\001 \001(\0162\026.ConstantProtocol.Type\"\260\001\n\004" +
      "Type\022\t\n\005READY\020\000\022\r\n\tNOT_READY\020\001\022\022\n\016STONE_" +
      "LOCATION\020\002\022\016\n\nINIT_STONE\020\003\022\016\n\nGAME_STATE" +
      "\020\004\022\023\n\017CLIENT_NUM_MINE\020\005\022\024\n\020CLIENT_NUM_OT" +
      "HER\020\006\022\022\n\016COUNT_DOWN_NUM\020\007\022\010\n\004DICE\020\010\022\010\n\004E" +
      "XIT\020\t\022\007\n\003WIN\020\nB\020B\016ConstantsProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConstantProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConstantProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConstantProtocol_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
